# Generated by Django 2.2.4 on 2019-12-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191211_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='lrtransation',
            name='lrtran_driverphone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
