# Generated by Django 2.2.4 on 2019-12-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lrtransation_lrtran_driverphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lrtransation',
            name='lrtran_driverphone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Driver Mob'),
        ),
    ]
