# Generated by Django 2.2.4 on 2019-10-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190930_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lrdocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrdoc_lrno', models.CharField(blank=True, max_length=50, null=True)),
                ('lrdoc_name', models.CharField(blank=True, max_length=50, null=True)),
                ('lrdoc_ctype', models.CharField(blank=True, max_length=200, null=True)),
                ('lrdoc_data', models.BinaryField(blank=True, null=True)),
                ('lrdoc_remarks', models.TextField(blank=True, null=True)),
                ('lrdoc_whmcode', models.IntegerField(blank=True, null=True)),
                ('lrdoc_makingtime', models.DateTimeField(blank=True, null=True)),
                ('lrdoc_makerid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lrdocument',
            },
        ),
        migrations.CreateModel(
            name='Lrgeneratingmtbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrg_tpcode', models.TextField(blank=True, null=True)),
                ('lrg_shiptocode', models.TextField(blank=True, null=True)),
                ('lrg_pl', models.TextField(blank=True, null=True)),
                ('lrg_div', models.TextField(blank=True, null=True)),
                ('lrg_matgrp', models.TextField(blank=True, null=True)),
                ('lrg_material', models.TextField(blank=True, null=True)),
                ('lrg_hsncode', models.TextField(blank=True, null=True)),
                ('lrg_taxinvno', models.TextField(blank=True, null=True)),
                ('lrg_intinvno', models.TextField(blank=True, null=True)),
                ('lrg_date', models.TextField(blank=True, null=True)),
                ('lrg_qty', models.IntegerField(blank=True, null=True)),
                ('lrg_frttyp', models.IntegerField(blank=True, null=True)),
                ('lrg_vehcode', models.TextField(blank=True, null=True)),
                ('lrg_unloadchrg', models.FloatField(blank=True, null=True)),
                ('lrg_unloadchremrks', models.TextField(blank=True, null=True)),
                ('lrg_courierid', models.IntegerField(blank=True, null=True)),
                ('lrg_courifrghchrg', models.FloatField(blank=True, null=True)),
                ('lrg_couriaddchrg', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('lrg_frghtchrgremrks', models.TextField(blank=True, null=True)),
                ('lrg_addchrgremarks', models.TextField(blank=True, null=True)),
                ('lrg_whmpntr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Companywarehousemaster')),
            ],
        ),
    ]
