# Generated by Django 2.2.4 on 2019-10-09 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_lrdocument_lrgeneratingmtbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiclemaster',
            fields=[
                ('vehmas_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vehmas_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('vehmas_catpntr', models.IntegerField(blank=True, null=True)),
                ('vehmas_frtyppntr', models.IntegerField(blank=True, null=True)),
                ('vehmas_modepntr', models.IntegerField(blank=True, null=True)),
                ('vehmas_slno', models.IntegerField(blank=True, null=True)),
                ('vehmas_active', models.CharField(blank=True, max_length=1, null=True)),
                ('vehmas_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('vehmas_makerid', models.IntegerField(blank=True, null=True)),
                ('vehmas_maketime', models.DateTimeField(blank=True, null=True)),
                ('vehmas_clntpntr', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lrgeneratingmtbl',
            name='lrg_frttyp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Freight Type'),
        ),
        migrations.AlterField(
            model_name='lrgeneratingmtbl',
            name='lrg_vehcode',
            field=models.TextField(blank=True, null=True, verbose_name='Vehicle Code'),
        ),
        migrations.AlterField(
            model_name='lrgeneratingmtbl',
            name='lrg_whmpntr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Companywarehousemaster', verbose_name='Consigner'),
        ),
    ]
