# Generated by Django 2.2.4 on 2019-10-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191009_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lrgeneratingmtbl',
            name='lrg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
