# Generated by Django 2.2.4 on 2019-09-30 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosingneemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consgnem_code', models.CharField(blank=True, max_length=50, null=True)),
                ('consgnem_name', models.CharField(blank=True, max_length=100, null=True)),
                ('consgnem_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('consgnem_address', models.CharField(blank=True, max_length=500, null=True)),
                ('consgnem_city', models.CharField(blank=True, max_length=50, null=True)),
                ('consgnem_district', models.CharField(blank=True, max_length=50, null=True)),
                ('consgnem_pincode', models.IntegerField(blank=True, null=True)),
                ('consgnem_routtyp', models.CharField(blank=True, max_length=20, null=True)),
                ('consgnem_gsttin', models.CharField(blank=True, max_length=25, null=True)),
                ('consgnem_pan', models.CharField(blank=True, max_length=25, null=True)),
                ('consgnem_distance', models.FloatField(blank=True, null=True)),
                ('cosngnrm_slno', models.IntegerField(blank=True, null=True)),
                ('consgnem_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('consgnem_active', models.CharField(blank=True, max_length=1, null=True)),
                ('consgnem_makerid', models.IntegerField(blank=True, null=True)),
                ('consgnem_maketime', models.DateTimeField(blank=True, null=True)),
                ('consgnem_routepntr', models.IntegerField(blank=True, null=True)),
                ('consgnem_clntpntr', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freightforroute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fght_fretypeptr', models.IntegerField(blank=True, null=True)),
                ('fght_routeptr', models.IntegerField(blank=True, null=True)),
                ('fght_basefreight', models.IntegerField(blank=True, null=True)),
                ('fght_kmrate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fght_vehcatptr', models.IntegerField(blank=True, null=True)),
                ('fght_slno', models.IntegerField(blank=True, null=True)),
                ('fght_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('fght_active', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freighttypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fretype_code', models.CharField(blank=True, max_length=50, null=True)),
                ('fretype_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('fretype_slno', models.IntegerField(blank=True, null=True)),
                ('fretype_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('fretype_active', models.CharField(blank=True, max_length=1, null=True)),
                ('fretype_nnc_code', models.CharField(blank=True, max_length=10, null=True)),
                ('fretype_whmcode', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procat_code', models.CharField(blank=True, max_length=25, null=True)),
                ('procat_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('procat_slno', models.IntegerField(blank=True, null=True)),
                ('procat_active', models.CharField(blank=True, max_length=1, null=True)),
                ('procat_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('procat_makerid', models.IntegerField(blank=True, null=True)),
                ('procat_maketime', models.DateTimeField(blank=True, null=True)),
                ('procat_clntpntr', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_code', models.CharField(blank=True, max_length=50, null=True)),
                ('prog_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('prog_slno', models.IntegerField(blank=True, null=True)),
                ('prog_rmrks', models.TextField(blank=True, null=True)),
                ('prog_status', models.CharField(blank=True, max_length=1, null=True)),
                ('prog_clntpntr', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtm_code', models.CharField(blank=True, max_length=50, null=True)),
                ('rtm_desc', models.CharField(max_length=100)),
                ('rtm_dist', models.CharField(max_length=50)),
                ('rtm_slno', models.IntegerField(blank=True, null=True)),
                ('rtm_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('rtm_active', models.CharField(blank=True, max_length=1, null=True)),
                ('rtm_details', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiclecategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehcat_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vehcat_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('vehcat_wtcapacity', models.FloatField(blank=True, null=True)),
                ('vehcat_length', models.FloatField(blank=True, null=True)),
                ('vehcat_width', models.FloatField(blank=True, null=True)),
                ('vehcat_ft', models.CharField(blank=True, max_length=50, null=True)),
                ('vehcat_kmrate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vehcat_slno', models.IntegerField(blank=True, null=True)),
                ('vehcat_active', models.CharField(blank=True, max_length=1, null=True)),
                ('vehcat_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('vehcat_makerid', models.IntegerField(blank=True, null=True)),
                ('vehcat_maketime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiclemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehmas_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vehmas_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('vehmas_frtyppntr', models.IntegerField(blank=True, null=True)),
                ('vehmas_modepntr', models.IntegerField(blank=True, null=True)),
                ('vehmas_slno', models.IntegerField(blank=True, null=True)),
                ('vehmas_active', models.CharField(blank=True, max_length=1, null=True)),
                ('vehmas_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('vehmas_makerid', models.IntegerField(blank=True, null=True)),
                ('vehmas_maketime', models.DateTimeField(blank=True, null=True)),
                ('vehmas_clntpntr', models.IntegerField(blank=True, null=True)),
                ('vehmas_catpntr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Vehiclecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Productsubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proscat_code', models.CharField(blank=True, max_length=50, null=True)),
                ('proscat_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('proscat_volume', models.FloatField(blank=True, null=True)),
                ('proscat_weight', models.FloatField(blank=True, null=True)),
                ('proscat_width', models.FloatField(blank=True, null=True)),
                ('proscat_length', models.FloatField(blank=True, null=True)),
                ('proscat_slno', models.IntegerField(blank=True, null=True)),
                ('proscat_active', models.CharField(blank=True, max_length=1, null=True)),
                ('proscat_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('proscat_makerid', models.IntegerField(blank=True, null=True)),
                ('proscat_maketime', models.DateTimeField(blank=True, null=True)),
                ('proscat_clntcode', models.IntegerField(blank=True, null=True)),
                ('proscat_procatpntr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Productmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promas_code', models.CharField(blank=True, max_length=50, null=True)),
                ('promas_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('promas_quantity', models.IntegerField(blank=True, null=True)),
                ('promas_slno', models.IntegerField(blank=True, null=True)),
                ('promas_active', models.CharField(blank=True, max_length=1, null=True)),
                ('promas_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('promas_makerid', models.IntegerField(blank=True, null=True)),
                ('promas_maketime', models.DateTimeField(blank=True, null=True)),
                ('promas_clntcode', models.IntegerField(blank=True, null=True)),
                ('promas_group_pntr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Productgroup')),
                ('promas_procat_pntr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Productcategory')),
                ('promas_proscat_pntr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Productsubcategory')),
            ],
        ),
    ]
