# Generated by Django 2.2.4 on 2019-12-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companymaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_masdesc', models.CharField(blank=True, max_length=50, null=True)),
                ('com_masname', models.CharField(blank=True, max_length=150, null=True)),
                ('com_masaddress', models.CharField(blank=True, max_length=250, null=True)),
                ('com_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('com_slno', models.IntegerField(blank=True, null=True)),
                ('com_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('com_active', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companyzonemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_zmasdesc', models.CharField(blank=True, max_length=50, null=True)),
                ('com_zmasname', models.CharField(blank=True, max_length=50, null=True)),
                ('com_zmascommaspntr', models.IntegerField(blank=True, null=True)),
                ('com_zmasslno', models.IntegerField(blank=True, null=True)),
                ('com_zmasremarks', models.CharField(blank=True, max_length=250, null=True)),
                ('com_zmasactive', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Couriermaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courmas_code', models.CharField(blank=True, max_length=50, null=True)),
                ('courmas_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('courmas_slno', models.IntegerField(blank=True, null=True)),
                ('courmas_active', models.CharField(blank=True, max_length=1, null=True)),
                ('courmas_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('courmas_makerid', models.IntegerField(blank=True, null=True)),
                ('courmas_maketime', models.DateTimeField(blank=True, null=True)),
                ('courmas_clntcode', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employeedesignationmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empdesig_code', models.CharField(blank=True, max_length=50, null=True)),
                ('empdesig_name', models.CharField(blank=True, max_length=150, null=True)),
                ('empdesig_slno', models.IntegerField(blank=True, null=True)),
                ('empdesig_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('empdesig_active', models.CharField(blank=True, max_length=1, null=True)),
                ('empdesig_makingtime', models.DateTimeField(blank=True, null=True)),
                ('empdesig_makerid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employeemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empmas_code', models.CharField(blank=True, max_length=50, null=True)),
                ('empmas_empdesigpntr', models.IntegerField(blank=True, null=True)),
                ('empmas_emptyppntr', models.IntegerField(blank=True, null=True)),
                ('empmas_empwhmcode', models.IntegerField(blank=True, null=True)),
                ('empmas_name', models.CharField(blank=True, max_length=150, null=True)),
                ('empmas_address', models.TextField(blank=True, null=True)),
                ('empmas_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('empmas_effectfrom', models.DateTimeField(blank=True, null=True)),
                ('empmas_retireddate', models.DateTimeField(blank=True, null=True)),
                ('empmas_slno', models.IntegerField(blank=True, null=True)),
                ('empmas_active', models.CharField(blank=True, max_length=1, null=True)),
                ('empmas_remarks', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employeetypemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emptyp_code', models.CharField(blank=True, max_length=50, null=True)),
                ('emptyp_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('emptyp_active', models.CharField(blank=True, max_length=1, null=True)),
                ('emptyp_slno', models.IntegerField(blank=True, null=True)),
                ('emptyp_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('emptyp_makingtime', models.DateTimeField(blank=True, null=True)),
                ('emptyp_makerid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firmmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frmm_code', models.CharField(blank=True, max_length=20, null=True)),
                ('frmm_name', models.CharField(blank=True, max_length=25, null=True)),
                ('frmm_adress', models.CharField(blank=True, max_length=250, null=True)),
                ('frmm_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('frmm_slno', models.IntegerField(blank=True, null=True)),
                ('frmm_active', models.CharField(blank=True, max_length=1, null=True)),
                ('frmm_remarks', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freightmodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fremodes_code', models.CharField(blank=True, max_length=50, null=True)),
                ('fremodes_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('fremodes_slno', models.IntegerField(blank=True, null=True)),
                ('fremodes_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('fremodes_active', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groupcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('group_code', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('div_no', models.CharField(blank=True, max_length=255, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
