# Generated by Django 2.2.4 on 2019-12-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_companymaster_companyzonemaster_couriermaster_employeedesignationmaster_employeemaster_employeetypem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='promas_group_pntr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='promas_procat_pntr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='promas_proscat_pntr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
    ]
