# Generated by Django 2.2.4 on 2019-12-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20191204_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='promas_group_pntr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Productgroup'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='promas_procat_pntr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Productcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='promas_proscat_pntr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Productsubcategory', verbose_name='Sub category'),
        ),
    ]
