# Generated by Django 2.2.4 on 2019-12-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20191204_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosingneemaster',
            name='consgnem_routepntr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Consignee Route'),
        ),
    ]
