# Generated by Django 2.2.4 on 2019-12-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(blank=True, max_length=200, null=True)),
                ('acc_shortname', models.CharField(blank=True, max_length=10, null=True)),
                ('acc_category', models.CharField(blank=True, choices=[('P', 'Payment'), ('R', 'Receipt')], max_length=1, null=True)),
                ('acc_status', models.CharField(blank=True, max_length=1, null=True)),
                ('acc_makerid', models.IntegerField(blank=True, null=True)),
                ('acc_maketime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accountstransactionlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logact_tranno', models.CharField(blank=True, max_length=50, null=True)),
                ('logact_reason', models.TextField(max_length=250)),
                ('logact_userid', models.IntegerField(blank=True, null=True)),
                ('logact_deltime', models.DateTimeField(blank=True, null=True)),
                ('logact_lrno', models.TextField(blank=True, null=True)),
                ('logact_whmcode', models.CharField(blank=True, max_length=10, null=True)),
                ('logact_acc_code', models.CharField(blank=True, max_length=30, null=True)),
                ('logact_glcode', models.CharField(blank=True, max_length=15, null=True)),
                ('logact_trandate', models.DateField(blank=True, null=True)),
                ('logact_vrno', models.CharField(blank=True, max_length=20, null=True)),
                ('logact_trantype', models.CharField(blank=True, max_length=1, null=True)),
                ('logact_month', models.CharField(blank=True, max_length=20, null=True)),
                ('logact_pay', models.TextField(blank=True, null=True)),
                ('logact_cash_rcpt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('logact_cash_pymnt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('logact_transfer_rcpt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('logact_transfer_pymnt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('logact_narration', models.TextField(blank=True, null=True)),
                ('logact_checkerid', models.IntegerField(blank=True, null=True)),
                ('logact_makerid', models.IntegerField(blank=True, null=True)),
                ('logact_makingtime', models.DateTimeField(blank=True, null=True)),
                ('logact_checkingtime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accountswarehousemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accwm_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('accwm_name', models.CharField(blank=True, max_length=150, null=True)),
                ('accwm_slno', models.IntegerField(blank=True, null=True)),
                ('accwm_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('accwm_active', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherNumbersettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vou_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('vou_no', models.CharField(blank=True, max_length=10, null=True)),
                ('vou_wrhcodepntr', models.IntegerField(blank=True, null=True)),
                ('vou_code', models.CharField(blank=True, max_length=10, null=True)),
                ('vou_slno', models.IntegerField(blank=True, null=True)),
                ('vou_active', models.CharField(blank=True, max_length=1, null=True)),
                ('vou_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('vou_clntcode', models.IntegerField(blank=True, null=True)),
                ('vou_city', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accountstransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_tranno', models.CharField(blank=True, max_length=50, null=True)),
                ('act_lrno', models.TextField(blank=True, null=True, verbose_name='LR Number')),
                ('act_glcode', models.CharField(blank=True, max_length=10, null=True)),
                ('act_trandate', models.DateField(blank=True, null=True)),
                ('act_vrno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Voucher Number')),
                ('act_trantype', models.CharField(blank=True, max_length=1, null=True)),
                ('act_pay', models.CharField(blank=True, max_length=150, null=True, verbose_name='Pay To')),
                ('act_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50, verbose_name='Expense For The Month')),
                ('act_cash_rcpt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Rupees')),
                ('act_cash_pymnt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Rupees')),
                ('act_transfer_rcpt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('act_transfer_pymnt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('act_narration', models.TextField(blank=True, null=True, verbose_name='Narration')),
                ('act_checkerid', models.IntegerField(blank=True, null=True)),
                ('act_makerid', models.IntegerField(blank=True, null=True)),
                ('act_makingtime', models.DateTimeField(blank=True, null=True, verbose_name='Voucher Date')),
                ('act_checkingtime', models.DateTimeField(blank=True, null=True)),
                ('act_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Cash Balance')),
                ('act_acc_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Accountmaster', verbose_name='Account Head')),
                ('act_whmcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Accountswarehousemaster', verbose_name='Warehouse')),
            ],
        ),
    ]
